### ISSUE TITLE
how to set cache expire time

### ISSUE THREAD

**Issue by licolas94** [gregurco/GuzzleBundleCachePlugin#11]
If I only want the cache to be valid within 5 minutes, and I need to request it again for the rest of the time, how can I set the effective time of the cache？Hope for help, thanks

**Comment by gregurco** [comment]
Hello @passer101 
Could you please describe in details your problem?

**Comment by petski** [comment]
@passer101 , does the example below fit your needs?

```yaml
 ...
            plugin:
                cache:
                    enabled: true
                    strategy: "your_app.greedy_strategy"
```

```yaml
...
services:
  your_app.greedy_strategy:
    class: Kevinrob\GuzzleCache\Strategy\GreedyCacheStrategy
    arguments:
      $cache: '@your_app.cache_store'
      $defaultTtl: 300
  your_app.cache_store:
    class: Kevinrob\GuzzleCache\Storage\Psr16CacheStorage
    arguments:
      $cache: '@your_app.cache'
  your_app.cache:
    class: Symfony\Component\Cache\Psr16Cache
    arguments:
      $pool: '@your_app.cache_pool'
  your_app.cache_pool:
    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    arguments:
      $namespace: 'your_app'
      $defaultLifetime: 300
      $directory: '%kernel.project_dir%/var/httpcache/'

```
